CREATE TABLE students(
LastName VARCHAR(30) NOT NULL,
FirstName VARCHAR(30) NOT NULL,
PersonalID VARCHAR(11) NOT NULL PRIMARY KEY,
Grade INT NOT NULL,
Email VARCHAR(20) NOT NULL,
Mess VARCHAR(250) NOT NULL
);